using System.Text;

using CrestCore.Contracts;

namespace CrestCore.Generator;

/// Emits `ContractCodec`, the core's reader and writer for every contract type.
internal static class CSharpCodecEmitter {
    #region Actions - Emitting

    public static string Emit(ContractSchema schema) {
        ArgumentNullException.ThrowIfNull(schema);
        var code = new StringBuilder();
        code.Append("""
            // <auto-generated/>
            // Generated by CrestCore/tools/CrestCore.Generator from the contract records. Do not edit.
            #nullable enable

            using CrestCore.Application;
            using CrestCore.Contracts;

            namespace CrestCore.Native;

            /// <summary>
            /// The wire codec for every contract type. A union is its root's tag, the
            /// index of the type in ordinal name order, followed by the type's fields.
            /// </summary>
            public static class ContractCodec {
                /// <summary>SHA-256 of the canonical contract schema.</summary>
                public static ReadOnlySpan<byte> Fingerprint => [
            """).Append('\n');
        code.Append("        ").Append(string.Join(", ", schema.Fingerprint.Select(value => $"0x{value:x2}"))).Append('\n');
        code.Append("    ];\n");
        code.Append('\n').Append("    /// <summary>SHA-256 of the engine contract alone, which an engine binding registers with.</summary>\n");
        code.Append("    public static ReadOnlySpan<byte> EngineFingerprint => [\n");
        code.Append("        ").Append(string.Join(", ", schema.EngineFingerprint.Select(value => $"0x{value:x2}"))).Append('\n');
        code.Append("    ];\n");
        foreach (var root in ContractRoot.All.Where(root => root.ReachesCore)) EmitRoot(code, schema, root);
        foreach (var narrowed in schema.Bases) EmitBase(code, schema, narrowed);
        foreach (var root in ContractRoot.All.Where(root => root.TravelsToCore)) EmitLimits(code, schema, root);
        EmitAnswers(code, schema);
        EmitEngineAnswers(code, schema);
        var direct = DirectOnly(schema);
        foreach (var record in schema.Records.Where(record => !direct.Contains(record.Type))) EmitRecord(code, schema, record);
        foreach (var item in schema.Enums.Where(item => !direct.Contains(item.Type))) EmitEnum(code, item);
        var tagged = schema.Sets.Where(set => !set.IsOpen && !direct.Contains(set.Type)).ToList();
        foreach (var set in tagged) EmitSet(code, set);
        if (tagged.Count > 0) EmitTagOf(code);
        code.Append("}\n");
        return code.ToString();
    }

    private static void EmitRoot(StringBuilder code, ContractSchema schema, ContractRoot root) {
        var members = schema.Members(root);
        string type = root.HasAnswer ? "object" : root.Name;
        code.Append('\n').Append($"    public static {type} Read{root}(WireReader reader) {{\n");
        code.Append("        int tag = reader.ReadTag();\n        switch (tag) {\n");
        foreach (var member in members)
            code.Append($"            case {member.Tag}: return Read{member.Name}(reader);\n");
        code.Append($"            default: throw new WireFormatException($\"Unknown {root} tag {{tag}}.\");\n        }}\n    }}\n");

        code.Append('\n').Append($"    public static void Write{root}(WireWriter writer, {type} value) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(writer);\n        ArgumentNullException.ThrowIfNull(value);\n");
        code.Append("        switch (value) {\n");
        foreach (var member in members) {
            code.Append($"            case {member.Name} member:\n");
            code.Append($"                writer.WriteTag({member.Tag});\n");
            code.Append($"                Write{member.Name}(writer, member);\n                break;\n");
        }
        code.Append($"            default: throw new ArgumentOutOfRangeException(nameof(value), value.GetType().Name, \"Not a contract {root}.\");\n");
        code.Append("        }\n    }\n");
    }

    /// A union base reads only the tags of its root's members that derive
    /// from it, and writes as its root does.
    private static void EmitBase(StringBuilder code, ContractSchema schema, RootField narrowed) {
        string name = narrowed.Base!.Name;
        code.Append('\n').Append($"    public static {name} Read{name}(WireReader reader) {{\n");
        code.Append("        int tag = reader.ReadTag();\n        switch (tag) {\n");
        foreach (var member in schema.Members(narrowed))
            code.Append($"            case {member.Tag}: return Read{member.Name}(reader);\n");
        code.Append($"            default: throw new WireFormatException($\"{narrowed.Root} tag {{tag}} is not a {name}.\");\n        }}\n    }}\n");
        code.Append('\n').Append($"    public static void Write{name}(WireWriter writer, {name} value) => Write{narrowed.Root}(writer, value);\n");
    }

    /// The most bytes one encoded message with a tag may take, which the
    /// dispatcher checks before it reads the message. A tag no type uses takes
    /// the default and then fails to decode.
    private static void EmitLimits(StringBuilder code, ContractSchema schema, ContractRoot root) {
        code.Append('\n').Append($"    /// <summary>The most bytes one encoded {string.Join(' ', Naming.Words(root.Name)).ToLowerInvariant()} with this tag may take.</summary>\n");
        code.Append($"    public static int Maximum{root}Bytes(int tag) => tag switch {{\n");
        foreach (var member in schema.Members(root).Where(member => member.MaximumBytes != MessageLimitAttribute.DefaultBytes))
            code.Append($"        {member.Tag} => {member.MaximumBytes},\n");
        code.Append($"        _ => {MessageLimitAttribute.DefaultBytes}\n    }};\n");
    }

    /// Writes the answer to a decoded query, so each query reaches whatever
    /// answers it, an app or the standalone answers, through its own type.
    private static void EmitAnswers(StringBuilder code, ContractSchema schema) {
        code.Append('\n').Append("    public static void WriteAnswer(WireWriter writer, IQueryAnswers answers, object query) {\n");
        code.Append("        ArgumentNullException.ThrowIfNull(answers);\n        ArgumentNullException.ThrowIfNull(query);\n");
        code.Append("        switch (query) {\n");
        foreach (var member in schema.Members(ContractRoot.Query)) {
            code.Append($"            case {member.Name} question:\n");
            code.Append($"                var answer{member.Tag} = answers.Query(question);\n");
            code.Append(Write(member.Answer!, $"answer{member.Tag}", "                ", $"Answer{member.Tag}"));
            code.Append("                break;\n");
        }
        code.Append("            default: throw new ArgumentOutOfRangeException(nameof(query), query.GetType().Name, \"Not a contract Query.\");\n");
        code.Append("        }\n    }\n");
    }

    /// Writes the answer to a decoded engine question, which the app answers
    /// for the engine that asked it, so each question reaches its answer
    /// through its own type.
    private static void EmitEngineAnswers(StringBuilder code, ContractSchema schema) {
        code.Append('\n').Append("    public static void WriteEngineAnswer(WireWriter writer, IEngineAnswers answers, Engine engine, object question) {\n");
        code.Append("        ArgumentNullException.ThrowIfNull(answers);\n        ArgumentNullException.ThrowIfNull(question);\n");
        code.Append("        switch (question) {\n");
        foreach (var member in schema.Members(ContractRoot.EngineQuestion)) {
            code.Append($"            case {member.Name} asked:\n");
            code.Append($"                var answer{member.Tag} = answers.Ask(engine, asked);\n");
            code.Append(Write(member.Answer!, $"answer{member.Tag}", "                ", $"Answer{member.Tag}"));
            code.Append("                break;\n");
        }
        code.Append("            default: throw new ArgumentOutOfRangeException(nameof(question), question.GetType().Name, \"Not a contract EngineQuestion.\");\n");
        code.Append("        }\n    }\n");
    }

    /// A record's resolved values follow its fields from the core. It
    /// computes them, so a reader of what it wrote passes over them. A message
    /// the platform sends holds seeds, and a record that has one also reads and
    /// writes it: its fields alone, with seeds in them.
    private static void EmitRecord(StringBuilder code, ContractSchema schema, ContractRecord record) {
        bool sent = schema.IsSent(record);
        EmitRecordCodec(code, schema, record, record.Name, record.Wire, seeds: sent);
        if (schema.HasSeed(record.Type)) EmitRecordCodec(code, schema, record, $"{record.Name}Seed", record.Fields, seeds: true);
    }

    private static void EmitRecordCodec(StringBuilder code, ContractSchema schema, ContractRecord record, string name,
        IReadOnlyList<ContractField> wire, bool seeds) {
        var passed = wire.Skip(record.Fields.Count).ToList();
        code.Append('\n').Append($"    public static {record.Name} Read{name}(WireReader reader) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(reader);\n");
        code.Append(passed.Count == 0 ? "        return new " : "        var value = new ").Append(record.Name).Append('(');
        code.Append(string.Join(",", record.Fields.Select(field => $"\n            {Read(field.Type, schema, seeds)}")));
        code.Append(");\n");
        foreach (var field in passed) code.Append($"        _ = {Read(field.Type, schema, seeds)};\n");
        if (passed.Count > 0) code.Append("        return value;\n");
        code.Append("    }\n");

        code.Append('\n').Append($"    public static void Write{name}(WireWriter writer, {record.Name} value) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(writer);\n        ArgumentNullException.ThrowIfNull(value);\n");
        foreach (var field in wire) code.Append(Write(field.Type, $"value.{field.Name}", "        ", field.Name, schema, seeds));
        code.Append("    }\n");
    }

    private static void EmitEnum(StringBuilder code, ContractEnum item) {
        string read = item.IsFlags
            ? $"reader.ReadFlags({item.Members.Aggregate(0, (mask, member) => mask | member.Value)})"
            : $"reader.ReadEnum({item.Members.Count})";
        code.Append('\n').Append($"    public static {item.Name} Read{item.Name}(WireReader reader) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(reader);\n");
        code.Append($"        return ({item.Name}){read};\n    }}\n");
        code.Append('\n').Append($"    public static void Write{item.Name}(WireWriter writer, {item.Name} value) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(writer);\n");
        code.Append("        writer.WriteEnum((int)value);\n    }\n");
    }

    /// A fixed set member travels as its index in the set's `All`.
    private static void EmitSet(StringBuilder code, ContractSet set) {
        code.Append('\n').Append($"    public static {set.Name} Read{set.Name}(WireReader reader) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(reader);\n");
        code.Append($"        return {set.Name}.All[reader.ReadEnum({set.Name}.All.Count)];\n    }}\n");
        code.Append('\n').Append($"    public static void Write{set.Name}(WireWriter writer, {set.Name} value) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(writer);\n        ArgumentNullException.ThrowIfNull(value);\n");
        code.Append($"        writer.WriteEnum(TagOf({set.Name}.All, value));\n    }}\n");
    }

    /// The records, enums and sets only the platform's direct path to an
    /// engine binding carries, which never reach the core.
    private static HashSet<Type> DirectOnly(ContractSchema schema) {
        var records = schema.Records.ToDictionary(record => record.Type);
        var direct = Reachable(records, ContractRoot.All.Where(root => !root.ReachesCore)
            .SelectMany(root => Carried(schema, root)));
        var core = Reachable(records, schema.Records.Select(record => record.Type).Where(type => !direct.Contains(type))
            .Concat(ContractRoot.All.Where(root => root.ReachesCore).SelectMany(root => Carried(schema, root))));
        direct.ExceptWith(core);
        return direct;
    }

    /// The types `root`'s members are, and the types their answers hold.
    private static IEnumerable<Type> Carried(ContractSchema schema, ContractRoot root) =>
        schema.Members(root).SelectMany(member =>
            member.Answer is { } answer ? Held(answer).Prepend(member.Record.Type) : [member.Record.Type]);

    /// `seeds` and every type their fields hold.
    private static HashSet<Type> Reachable(Dictionary<Type, ContractRecord> records, IEnumerable<Type> seeds) {
        var reached = new HashSet<Type>();
        var pending = new Stack<Type>(seeds);
        while (pending.TryPop(out var type)) {
            if (!reached.Add(type) || !records.TryGetValue(type, out var record)) continue;
            foreach (var field in record.Wire)
                foreach (var held in Held(field.Type)) pending.Push(held);
        }
        return reached;
    }

    private static IEnumerable<Type> Held(FieldType type) => type switch {
        RecordField record => [record.Type],
        EnumField item => [item.Type],
        SetField set => [set.Type],
        ListField list => Held(list.Element),
        OptionalField optional => Held(optional.Value),
        _ => []
    };

    private static void EmitTagOf(StringBuilder code) => code.Append("""

            /// <summary>A fixed set member's wire tag: its index in the set's <c>All</c>.</summary>
            private static int TagOf<T>(IReadOnlyList<T> all, T value) where T : class {
                for (int tag = 0; tag < all.Count; tag++)
                    if (ReferenceEquals(all[tag], value)) return tag;
                throw new ArgumentOutOfRangeException(nameof(value), value, "Not a member of its fixed set.");
            }

        """);

    #endregion

    #region Actions - Fields

    /// A field's reader. With `seeds`, a record that has a seed reads it.
    private static string Read(FieldType type, ContractSchema? schema = null, bool seeds = false) => type switch {
        PrimitiveField primitive => $"reader.Read{Method(primitive.Kind)}()",
        EnumField item => $"Read{item.Type.Name}(reader)",
        SetField set => $"Read{set.Type.Name}(reader)",
        RecordField record => $"Read{record.Type.Name}{Seed(record, schema, seeds)}(reader)",
        RootField { Base: { } narrowed } => $"Read{narrowed.Name}(reader)",
        RootField root => $"Read{root.Root}(reader)",
        ListField list => $"reader.ReadList(() => {Read(list.Element, schema, seeds)})",
        OptionalField optional => $"reader.ReadPresence() ? ({TypeName(optional)}){Read(optional.Value, schema, seeds)} : null",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    /// The suffix of the reader or writer of a record's seed, where `seeds`
    /// asks for one and the record has one.
    private static string Seed(RecordField record, ContractSchema? schema, bool seeds) =>
        seeds && schema!.HasSeed(record.Type) ? "Seed" : "";

    /// Pattern variables in an `if` share the method's scope, so each carries
    /// the field's name as `scope`.
    private static string Write(FieldType type, string value, string indent, string scope, ContractSchema? schema = null, bool seeds = false) => type switch {
        PrimitiveField primitive => $"{indent}writer.Write{Method(primitive.Kind)}({value});\n",
        EnumField item => $"{indent}Write{item.Type.Name}(writer, {value});\n",
        SetField set => $"{indent}Write{set.Type.Name}(writer, {value});\n",
        RecordField record => $"{indent}Write{record.Type.Name}{Seed(record, schema, seeds)}(writer, {value});\n",
        RootField root => $"{indent}Write{root.Root}(writer, {value});\n",
        ListField list => $"{indent}writer.WriteCount({value}.Count);\n"
            + $"{indent}foreach (var item{scope} in {value}) {{\n"
            + Write(list.Element, $"item{scope}", indent + "    ", $"{scope}Item", schema, seeds)
            + $"{indent}}}\n",
        OptionalField optional => $"{indent}if ({value} is {{ }} present{scope}) {{\n"
            + $"{indent}    writer.WritePresence(true);\n"
            + Write(optional.Value, $"present{scope}", indent + "    ", $"{scope}Value", schema, seeds)
            + $"{indent}}} else {{\n{indent}    writer.WritePresence(false);\n{indent}}}\n",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    private static string Method(Primitive kind) => kind switch {
        Primitive.Int => "Int32",
        Primitive.Long => "Int64",
        Primitive.ULong => "UInt64",
        _ => kind.ToString()
    };

    private static string TypeName(FieldType type) => type switch {
        PrimitiveField { Kind: Primitive.Bool } => "bool",
        PrimitiveField { Kind: Primitive.Int } => "int",
        PrimitiveField { Kind: Primitive.Long } => "long",
        PrimitiveField { Kind: Primitive.ULong } => "ulong",
        PrimitiveField { Kind: Primitive.Double } => "double",
        PrimitiveField { Kind: Primitive.String } => "string",
        PrimitiveField { Kind: Primitive.Guid } => "Guid",
        PrimitiveField { Kind: Primitive.Date } => "DateTimeOffset",
        PrimitiveField { Kind: Primitive.Duration } => "TimeSpan",
        PrimitiveField { Kind: Primitive.Bytes } => "byte[]",
        EnumField item => item.Type.Name,
        SetField set => set.Type.Name,
        RecordField record => record.Type.Name,
        RootField { Base: { } narrowed } => narrowed.Name,
        RootField root => root.Root.ToString(),
        ListField list => $"IReadOnlyList<{TypeName(list.Element)}>",
        OptionalField optional => $"{TypeName(optional.Value)}?",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    #endregion
}
