using System.Text;

namespace CrestCore.Generator;

/// Emits the core's handler interfaces and `ContractDispatch`: for each union
/// family of a root the core reads, an interface with one `Handle` overload
/// per case, and a `Dispatch` extension that routes a message to its case's
/// overload. A receiver implements the interface of each family it owns, so a
/// new case without a handler fails to compile. A family whose messages are
/// questions answers each case with the case's own answer; any other family
/// has a void handler and one that returns a result of the receiver's choice.
/// Both take a context: what every case of the receiver needs for one call.
internal static class CSharpHandlerEmitter {
    #region Static Variables

    private const string Context = "TContext";
    private const string Result = "TResult";
    private const string Answer = "TAnswer";

    #endregion

    #region Actions - Emitting

    public static string Emit(ContractSchema schema) {
        ArgumentNullException.ThrowIfNull(schema);
        var families = schema.Unions.Where(family => family.Root.CoreHandles).ToList();
        var code = new StringBuilder();
        code.Append("""
            // <auto-generated/>
            // Generated by CrestCore/tools/CrestCore.Generator from the contract records. Do not edit.
            #nullable enable

            using CrestCore.Contracts;

            namespace CrestCore.Application;

            """);
        foreach (var family in families) EmitInterfaces(code, family);
        code.Append('\n').Append("/// <summary>Routes each message to its handler's overload for its case.</summary>\n");
        code.Append("internal static class ContractDispatch {\n");
        foreach (var (family, index) in families.Select((family, index) => (family, index))) {
            if (index > 0) code.Append('\n');
            EmitDispatch(code, family);
        }
        code.Append("}\n");
        return code.ToString();
    }

    private static void EmitInterfaces(StringBuilder code, ContractFamily family) {
        string name = Interface(family);
        if (family.Root.HasAnswer) {
            code.Append('\n').Append($"/// <summary>Answers each case of <c>{family.Name}</c> with its own answer.</summary>\n");
            code.Append($"internal interface {name}<{Context}> {{\n");
            foreach (var type in family.Cases)
                code.Append(ContractFamily.IsFamily(type)
                    ? $"    {Answer} Handle<{Answer}>({ContractFamily.NameOf(type)}<{Answer}> message, {Context} context);\n"
                    : $"    {TypeName(family.Root.AnswerOf(type)!)} Handle({type.Name} message, {Context} context);\n");
            code.Append("}\n");
            return;
        }
        code.Append('\n').Append($"/// <summary>Handles each case of <c>{family.Name}</c>.</summary>\n");
        code.Append($"internal interface {name}<{Context}> {{\n");
        foreach (var type in family.Cases) code.Append($"    void Handle({type.Name} message, {Context} context);\n");
        code.Append("}\n");
        code.Append('\n').Append($"/// <summary>Handles each case of <c>{family.Name}</c>, answering a result of the receiver's choice.</summary>\n");
        code.Append($"internal interface {name}<{Context}, {Result}> {{\n");
        foreach (var type in family.Cases) code.Append($"    {Result} Handle({type.Name} message, {Context} context);\n");
        code.Append("}\n");
    }

    private static void EmitDispatch(StringBuilder code, ContractFamily family) {
        string name = Interface(family);
        string unknown = $"            _ => throw new ArgumentOutOfRangeException(nameof(message), message.GetType().Name, "
            + $"\"Not a contract {family.Name}.\")\n";
        if (family.Root.HasAnswer) {
            code.Append($"    public static {Answer} Dispatch<{Answer}, {Context}>(this {family.Name}<{Answer}> message, {name}<{Context}> handler, "
                + $"{Context} context) {{\n");
            EmitChecks(code);
            code.Append("        return message switch {\n");
            foreach (var type in family.Cases)
                code.Append(ContractFamily.IsFamily(type)
                    ? $"            {ContractFamily.NameOf(type)}<{Answer}> family => handler.Handle(family, context),\n"
                    : $"            {type.Name} @case => ({Answer})(object)handler.Handle(@case, context),\n");
            code.Append(unknown).Append("        };\n    }\n");
            return;
        }
        code.Append($"    public static void Dispatch<{Context}>(this {family.Name} message, {name}<{Context}> handler, {Context} context) {{\n");
        EmitChecks(code);
        code.Append("        switch (message) {\n");
        foreach (var type in family.Cases) code.Append($"            case {type.Name} @case: handler.Handle(@case, context); return;\n");
        code.Append($"            default: throw new ArgumentOutOfRangeException(nameof(message), message.GetType().Name, "
            + $"\"Not a contract {family.Name}.\");\n");
        code.Append("        }\n    }\n\n");
        code.Append($"    public static {Result} Dispatch<{Context}, {Result}>(this {family.Name} message, {name}<{Context}, {Result}> handler, "
            + $"{Context} context) {{\n");
        EmitChecks(code);
        code.Append("        return message switch {\n");
        foreach (var type in family.Cases) code.Append($"            {type.Name} @case => handler.Handle(@case, context),\n");
        code.Append(unknown).Append("        };\n    }\n");
    }

    private static void EmitChecks(StringBuilder code) =>
        code.Append("        ArgumentNullException.ThrowIfNull(message);\n        ArgumentNullException.ThrowIfNull(handler);\n");

    /// `PageIntent`'s handler is `IPageIntentHandler`.
    public static string Interface(ContractFamily family) {
        ArgumentNullException.ThrowIfNull(family);
        return $"I{family.Name}Handler";
    }

    /// A C# spelling of an answer's type.
    private static string TypeName(Type type) => type.IsGenericType
        ? $"{ContractFamily.NameOf(type.GetGenericTypeDefinition())}<{string.Join(", ", type.GetGenericArguments().Select(TypeName))}>"
        : type.Name;

    #endregion
}
